<div data-placeholder="cartpopup" style="display: none;">
    <div data-bind="scope: 'cartpopup'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                            "cartpopup": {
                                "component": "Magelearn_CartPopup/js/cartpopup",
                                "shoppingCartUrl": "<?php echo $block->getShoppingCartUrl(); ?>",
                                "cartMessage": "<?php echo $block->getCartMessage(); ?>",
                                "successIcon" : "<?php echo $block->getSuccessIcon(); ?>",
                                "carouselAutoPlay" : "<?php echo $block->getCarouselAutoPlay(); ?>"
                            }
                    }
                }
            }
    }
</script>